app:
  port: 8080
  
jwt:
  secret: JWT_SCERET_KEY_LEO-MESSI
  
postgres:
  host: localhost
  port: 5433
  user: ecommerce_user
  password: ecommerce_pass
  dbname: ecommerce_db

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

